### PR TITLE
Bump kpromo to v4.0.0

### PR DESCRIPTION
**Pull request by jeremyrickard**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

Update release versions to v4.0.0

#### Which issue(s) this PR fixes:

ref: #917 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by puerco — APPROVED** [review]
Thanks!

**Comment by jeremyrickard** [comment]
Sorry for the force push, I realized I signed my commit with the wrong yubikey. Corrected that w/ the push.

**Comment by jeremyrickard** [comment]
closing to try and retry easycla

**Pull request merged**
