### PR TITLE
Switch to golang 1.19

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Switching to the latest go release.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated golang to 1.19.
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks
/lgtm

**Comment by cpanato** [comment]
@saschagrunert PTAL https://github.com/kubernetes/test-infra/pull/27888

**Comment by saschagrunert** [comment]
So, let's check if a rebase works for this one.

**Pull request merged**
