### PR TITLE
Move container image promotion commands into `kpromo`

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

- Move container image promotion commands into `kpromo`
  Command ergonomics remain roughly the same e.g.,
  `cip run ...` becomes `kpromo cip ...`
- Update locations/invocations of container image promotion command
- Dockerfile: Reduce production image size with cloud-sdk:slim
- Merge `kpromo` image building into primary Dockerfile
- Drop `STABLE_` prefix for variables
  ...this is a bazel-ism and no longer required.
- cloudbuild.yaml: Plumb `IMG_VERSION`

Signed-off-by: Stephen Augustus <foo@auggie.dev>

#### Special notes for your reviewer:

~~A large majority of the tests will fail because of file location changes.~~

#### Does this PR introduce a user-facing change?

```release-note
- Move container image promotion commands into `kpromo`
  Command ergonomics remain roughly the same e.g.,
  `cip run ...` becomes `kpromo cip ...`
```

### CODE REVIEW

**Comment by justaugustus** [comment]
### TODO

- [ ] Tool doesn't actually have build info in the container:

```console
❯ docker run --rm gcr.io/k8s-staging-releng-test/cip:v20210923-v3.2.1-11-g141fb03 "kpromo cip version"
GitVersion:
GitCommit:
GitTreeState:
BuildDate:
GoVersion:     go1.17.1
Compiler:      gc
Platform:      linux/amd64
```

**Comment by justaugustus** [comment]
ref: https://github.com/kubernetes-sigs/promo-tools/pull/434/commits/d1f06efec3088b07e4e7e7bdf1fdf4fe2bae010d
Screen Shot 2021-09-23 at 19 32 06

Much better on the image size, but still unnecessarily large, so I'll iterate on that a bit.
(Some of the repo contents are likely getting copied from the builder image through to the final image.)

**Comment by cpanato** [comment]
> ### TODO
> * [ ]  Tool doesn't actually have build info in the container:
> 
> ```
> ❯ docker run --rm gcr.io/k8s-staging-releng-test/cip:v20210923-v3.2.1-11-g141fb03 "kpromo cip version"
> GitVersion:
> GitCommit:
> GitTreeState:
> BuildDate:
> GoVersion:     go1.17.1
> Compiler:      gc
> Platform:      linux/amd64
> ```

can a take this as a follow up pr?

**Comment by justaugustus** [comment]
> can a take this as a follow up pr?

@cpanato -- Sure thing! I've opened https://github.com/kubernetes-sigs/promo-tools/issues/436 for this and assigned it to you, but I'd say give it a few days (since I'm going to move a few more things around). :)

**Comment by justaugustus** [comment]
/assign @cpanato @puerco @Verolop @xmudrii 
cc: @kubernetes-sigs/release-engineering

**Comment by justaugustus** [comment]
Ready for review :)

**Review by cpanato — APPROVED** [review]
thanks!
/lgtm

**Pull request merged**
