### PR TITLE
kpromo sigcheck: Verify and fix missing image signatures

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR introduces a new `kpromo sigcheck` subcommand that checks images for missing or inconsistent
signatures. Without passing the `--confirm` flag, kpromo will only check the signatures and output a dry run
of what it would do.

`kpromo sigcheck` takes image references as positional arguments, if not specified, it will check all the latest images uploaded to the kubernetes registry.

#### Which issue(s) this PR fixes:

This is intended to be a periodic job that ensures that images are properly signed.

#### Special notes for your reviewer:

**Note** this change is a different code path than the usual image promotion. So it should not affect any current process

Signing and replicating are untested for now, although it is mostly the same code we already had. We need to write some tests too.

To test the verification, run `kpromo` from my branch and test against the images, without `--confirm` nothing is changed. For example, this is an image missing signatures, and the next one is properly signed:

```
go run ./cmd/kpromo/ sigcheck registry.k8s.io/kube-scheduler:v1.24.11
NFO Fetching latest promoted images              
INFO Checking signatures                          
INFO Sending GET request to https://github.com/kubernetes/k8s.io/raw/main/k8s.gcr.io/manifests/k8s-staging-kubernetes/promoter-manifest.yaml 
INFO Checking signatures in 23 mirrors            
INFO Checking 23 objects for signatures           
INFO Fixing 1 unsigned images                     
``

```
go run ./cmd/kpromo/ sigcheck registry.k8s.io/kube-scheduler:v1.24.10
INFO Fetching latest promoted images              
INFO Checking signatures                          
INFO Sending GET request to https://github.com/kubernetes/k8s.io/raw/main/k8s.gcr.io/manifests/k8s-staging-kubernetes/promoter-manifest.yaml 
INFO Checking signatures in 23 mirrors            
INFO Checking 23 objects for signatures           
INFO Signature consistency OK!                 
```

#### Does this PR introduce a user-facing change?


```release-note
New `kpromo sigcheck` subcommand to verify and optionally fix images that may hay missing or inconsistent signatures.
```

### CODE REVIEW

**Comment by puerco** [comment]
OK, this one should be ready to go. It can now index the latest modified images in the registry.  Here is an example run (output trimmed):

```
time go run ./cmd/kpromo/ sigcheck 
INFO Fetching latest promoted images              
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images 
INFO Indexing 28 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-builder 
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-manager 
INFO Indexing 4 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-manager/kube-addon-manager 
INFO Indexing 27 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-resizer 
INFO Indexing 2 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/aggregator 
INFO Indexing 1 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/alpine-with-bash 
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apisnoop 
INFO Indexing 1 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apisnoop/auditlogger 
INFO Indexing 2 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apisnoop/snoopdb 
INFO Indexing 3 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apparmor-loader 
[ --- trimmed --- ]
INFO Indexing 2080 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes/kube-apiserver 
INFO Indexing 2074 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes/kube-controller-manager 
INFO Indexing 2079 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes/kube-proxy 
INFO Indexing 2081 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes/kube-scheduler 
INFO Indexing 68 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes/pause 
[ --- trimmed --- ]
INFO Indexing 3 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/webhooks-publisher 
INFO Indexing 62 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/zeppelin 
INFO Indexing 1 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/zeppelin-proxy 
INFO Indexing 1 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/zookeeper-install 
INFO Indexing 2 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/zookeeper-install-3.5.0-alpha 
INFO Checking signatures                          
INFO Sending GET request to https://github.com/kubernetes/k8s.io/raw/main/k8s.gcr.io/manifests/k8s-staging-kubernetes/promoter-manifest.yaml 
INFO Checking 91 images for signatures, each in 23 mirrors 
INFO Checking registry.k8s.io/build-image/debian-base:bullseye-v1.4.3 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/build-image/debian-iptables:bullseye-v1.5.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/build-image/distroless-iptables:v0.2.1 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/capi-operator/cluster-api-operator:v0.1.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.9.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.26.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.24.11 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.25.7 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.26.3-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.23.17 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.25.8-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.23.18-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/conformance:v1.24.12-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.24.12-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.24.11 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.25.8-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.26.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.25.7 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.23.17 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.26.3-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-apiserver:v1.23.18-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.24.12-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.23.17 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.26.3-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.26.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.24.11 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.25.7 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.25.8-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-controller-manager:v1.23.18-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.26.3-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.24.12-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.26.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.25.8-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.24.11 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.25.7 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.23.17 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-proxy:v1.23.18-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.26.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.25.8-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.24.12-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.23.17 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.24.11 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.26.3-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.23.18-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-scheduler:v1.25.7 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.25.7 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.23.17 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.24.12-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.23.18-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.26.3-rc.0 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.26.2 for signatures in 23 mirrors 
INFO Checking registry.k8s.io/kubernetes/conformance:v1.24.11 for signatures in 23 mirrors
```

**Review by cpanato — APPROVED** [review]
/lgtm
Thanks for doing this
/hold for more eyes in case is needed

**Review by jimangel — COMMENTED** [review]
I ran a few tests, is there any way we can confirm the signature checks work with a sample image first? Unless everyone else is confident in the code doing what we think it should with `--confirm`?

My steps:

```
# copy repo and work out of branch
git clone https://github.com/puerco/promo-tools.git puerco-clone-promo-tools
cd puerco-clone-promo-tools
git checkout sigcheck

go install ./cmd/kpromo/...
# without --confirm nothing is changed.
go run ./cmd/kpromo/ sigcheck registry.k8s.io/kube-scheduler:v1.24.11
```

Output:

```
c07cc.sig to asia-east1-docker.pkg.dev/k8s-artifacts-prod/images/kube-scheduler:sha256-d735e3eeaeb82de99fa35e013d54a944dfacea76d83c2371e45e857a538c07cc.sig  
INFO Fixing 0 images with partial signatures 
```

Testing more:

```shell
time go run ./cmd/kpromo/ sigcheck
```

Output:

```
INFO Fetching latest promoted images              
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images 
INFO Indexing 28 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-builder 
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-manager 
INFO Indexing 4 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-manager/kube-addon-manager 
INFO Indexing 27 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/addon-resizer 
INFO Indexing 2 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/aggregator 
INFO Indexing 1 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/alpine-with-bash 
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apisnoop 
INFO Indexing 1 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apisnoop/auditlogger 
INFO Indexing 2 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apisnoop/snoopdb 
INFO Indexing 3 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/apparmor-loader 
INFO Indexing 0 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/artifact-promoter 
INFO Indexing 18 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/artifact-promoter/cip 
INFO Indexing 9 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/artifact-promoter/cip-auditor 
INFO Indexing 51 images from us-central1-docker.pkg.dev/k8s-artifacts-prod/images/artifact-promoter/kpromo 
        ........
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to us-east4-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to us-south1-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to europe-north1-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to europe-west8-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to europe-west9-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to southamerica-west1-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to asia.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to asia-east1-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to asia-south1-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
INFO  (NOOP) replicating eu.gcr.io/k8s-artifacts-prod/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig to australia-southeast1-docker.pkg.dev/k8s-artifacts-prod/images/kube-controller-manager:sha256-5dce7ac51e2a936b287eff24e38f4fc1c1efd558bb3f46b1b4082c39700781f4.sig  
        ........
go run ./cmd/kpromo/ sigcheck  474.67s user 291.05s system 30% cpu 41:37.12 total
```

The full check took roughly 8 minutes and appears to have caught the unsigned images.

/lgtm

**Review by xmudrii — APPROVED** [review]
Looks good to me! I tried testing it, but I'm not able to compile `kpromo` because I use Go 1.20.1, but some dependencies require Go 1.19.5.

```
# internal/goarch
compile: version "go1.19.5" does not match go tool version "go1.20.1"
# internal/goos
compile: version "go1.19.5" does not match go tool version "go1.20.1"
...
# cloud.google.com/go/storage/internal
compile: version "go1.19.5" does not match go tool version "go1.20.1"
# github.com/aws/aws-sdk-go/aws/client/metadata
compile: version "go1.19.5" does not match go tool version "go1.20.1"
```

I'll create a tracking issue for updating promo-tools to Go 1.20.

**Review by palnabarun — APPROVED** [review]
Verified running the subcommand. ✅ 

/lgtm

**Pull request merged**
