### PR TITLE
kpromo: add quotes around reviewers in command print

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
#### Does this PR introduce a user-facing change?

```release-note
kpromo: add quotes around reviewers in command print
```

### CODE REVIEW

**Comment by puerco** [comment]
Thanks!
/lgtm
/approve
/release-note-none

(Follow-up to https://github.com/kubernetes/k8s.io/pull/3129 )

**Comment by CecileRobertMichon** [comment]
@puerco would it be possible to create a new beta tag with theses changes?

**Comment by justaugustus** [comment]
> @puerco would it be possible to create a new beta tag with these changes?

@CecileRobertMichon -- Here you go! https://github.com/kubernetes-sigs/promo-tools/releases/tag/v3.3.0-beta.3

**Pull request merged**
