### PR TITLE
Remove dead checks in image promoter

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
These are only called by tests. This also hides a flag that was unused (for image size).

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This removes a bunch of dead code to make it easier to understand what's going on in the promoter.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

I'm sorry.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/cc @puerco

### CODE REVIEW

**Review by puerco — COMMENTED** [review]
I'm leaving this comment here for future reference if we need this test again :point_down:

**Comment by puerco** [comment]
The linter failed, but otherwise lgtm

**Comment by puerco** [comment]
it looks like it needs a rebase, weird that prow didn't catch it

**Comment by puerco** [comment]
what.is.this ..   :|

**Comment by puerco** [comment]
> Weird that it's trying to fetch this branch from this repo and not my fork?
Ah yeah at the bottom. wtf.

**Comment by eddiezane** [comment]
https://kubernetes.slack.com/archives/C7J9RP96G/p1680020553428789

**Comment by puerco** [comment]
A revert to prow is going on here:  https://github.com/kubernetes/test-infra/pull/29167

**Pull request merged**
