### PR TITLE
releng: Bump promoter to v3.5.0

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- releng: Bump promoter to v3.5.0

/assign @puerco @saschagrunert @ameukam 
cc @kubernetes-sigs/release-engineering 

#### Which issue(s) this PR fixes:

Related to:
  - https://github.com/kubernetes-sigs/promo-tools/issues/752

#### Does this PR introduce a user-facing change?

```release-note
releng: Bump promoter to v3.5.0
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by palnabarun — APPROVED** [review]
/lgtm
/approve

**Comment by cpanato** [comment]
going to hold till next week

**Comment by upodroid** [comment]
Can we merge this change first? https://github.com/kubernetes-sigs/promo-tools/pull/669

**Comment by cpanato** [comment]
> Can we merge this change first? #669

we also are waiting for other things

**Pull request merged**
