### PR TITLE
kpromo(pr): Minor cleanups

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup
/area dependency

#### What this PR does / why we need it:

- kpromo: Replace fork functions with sigs.k8s.io/release-sdk analogs
- kpromo(pr): Only append "releng: " to commit msg for RelEng promotions (follow-up to https://github.com/kubernetes-sigs/promo-tools/pull/458#discussion_r751817059, cc: @CecileRobertMichon)

Depends on:
- https://github.com/kubernetes-sigs/promo-tools/pull/458
- https://github.com/kubernetes-sigs/release-sdk/pull/13

#### Does this PR introduce a user-facing change?

```release-note
- kpromo: Replace fork functions with sigs.k8s.io/release-sdk analogs
  Using sigs.k8s.io/release-sdk@v0.5.0
- kpromo(pr): Only append "releng: " to commit msg for RelEng promotions
```

### CODE REVIEW

**Comment by justaugustus** [comment]
> Depends on:
> 
>     * [kpromo: Add `krel promote-images` functionality #458](https://github.com/kubernetes-sigs/promo-tools/pull/458)
> 
>     * [github: Add forking functionality from `krel release-notes` release-sdk#13](https://github.com/kubernetes-sigs/release-sdk/pull/13)

/hold until the referenced PRs are merged, changes are rebased out, and go.mod `replace` is removed

**Comment by justaugustus** [comment]
> /hold until the referenced PRs are merged, changes are rebased out, and go.mod `replace` is removed

/hold cancel
All conditions have been met.

**Comment by justaugustus** [comment]
/assign @puerco @Verolop 
cc: @kubernetes-sigs/release-engineering

**Review by puerco — APPROVED** [review]
/lgtm

**Pull request merged**
