### PR TITLE
kpromo pr: Allow sorting output manifest by tags instead of digest

### LINKED ISSUE #473: cip-mm sort by tag instead of checksum
#### What would you like to be added:
Currently, if you use cip-mm to promote images, it sorts the generated file by the checksum of the promoted container images. Ideally it would allow sorting the generated file by tag instead or have an option to provide that as a argument.

#### Why is this needed:
If you promote images for multiple architectures it makes it very difficult to spot if all of them are there when looking at the file.
See for example: https://github.com/kubernetes/k8s.io/pull/2595/files

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it: 
This PRs allows optionally sorting manifests by tag so they are easier to review by human reviewers. The default is the current behavior of sorting by image digest.

#### Which issue(s) this PR fixes:

Fixes #473 

#### Does this PR introduce a user-facing change?

```release-note
kpromo pr: Allow sorting output manifest by tags instead of digest
```

### CODE REVIEW

**Comment by fabriziopandini** [comment]
Thanks, @CecileRobertMichon, this looks great!

**Review by cpanato — APPROVED** [review]
it looks great!
/lgtm
/hold

**Comment by CecileRobertMichon** [comment]
@puerco do I need to change anything in this PR after #494 merged?

**Comment by CecileRobertMichon** [comment]
Used this branch to promote CAPI v1.1.2 https://github.com/kubernetes/k8s.io/pull/3422

**Comment by CecileRobertMichon** [comment]
rebased

@cpanato are we waiting for anyone specific to comment on this? Would love to get this merged soon so we can start using it

**Comment by cpanato** [comment]
> rebased
> 
> @cpanato are we waiting for anyone specific to comment on this? Would love to get this merged soon so we can start using it

was waiting for others to comment, but it is been a long time, let's get this in!
/unhold
/lgtm

**Comment by CecileRobertMichon** [comment]
@justaugustus did you re-add the hold intentionally?

**Comment by justaugustus** [comment]
> @justaugustus did you re-add the hold intentionally?

Yep! A few comments here: https://github.com/kubernetes-sigs/promo-tools/pull/493#pullrequestreview-891530774

**Comment by CecileRobertMichon** [comment]
> Let's just make this the only behavior.

My concern here is that everyone using the tool will see a huge diff the first time then run the new version since all the previous images will get reordered. I was also under the impression from the discussion in the issue (#473) that some projects prefer sorting by image digest since that's more "machine-readable". I think it makes more sense to start with an optional opt in sort so projects can keep using the tool without being affected and then if the demand is there move this to default later on and deprecate the sorted by digest functionality (or not).

> We need a lexicographical sort, as opposed to strictly SemVer.

Thanks for catching that, I assumed all tags would be semver. Will apply these changes when I get a chance.

**Comment by justaugustus** [comment]
> My concern here is that everyone using the tool will see a huge diff the first time then run the new version since all the previous images will get reordered.

That's fine; we can announce the changes.

> I was also under the impression from the discussion in the issue (#473) that some projects prefer sorting by image digest since that's more "machine-readable".

Initially, I thought you wanted to introduce a new structure altogether.
The concern was that co-mingling the old and new structures would cause unexpected unmarshalling errors.

Given it's the same data structure, the promoter isn't going to need to care about what order the content is in.

> I think it makes more sense to start with an optional opt in sort so projects can keep using the tool without being affected and then if the demand is there move this to default later on and deprecate the sorted by digest functionality (or not).

Variance introduces risk.
I'd prefer a single solution/codepath to debug than multiple.
(Part of why I suggested deprecating `cip-mm` in https://github.com/kubernetes-sigs/promo-tools/issues/473#issuecomment-991167871, since `cip-mm` and `kpromo pr`'s behavior is already divergent.)

> > We need a lexicographical sort, as opposed to strictly SemVer.
> 
> Thanks for catching that, I assumed all tags would be semver. Will apply these changes when I get a chance.

SGTM!

**Comment by CecileRobertMichon** [comment]
@justaugustus added a commit to always sort by tags and another to sort lexicographically. PTAL when you get a chance.

@fabriziopandini FYI the tags won't be sorted by semver version unfortunately as @justaugustus pointed out that image tags are not always semver compliant so we need to sort lexicographically. Still an improvement though.

**Review by justaugustus — APPROVED** [review]
Awesome! Thanks @CecileRobertMichon!! 🎉 
/hold cancel

**Comment by CecileRobertMichon** [comment]
/hold 

should I squash?

**Comment by CecileRobertMichon** [comment]
/hold cancel 

@justaugustus I squashed

How do we announce this so it doesn't surprise folks?

**Comment by justaugustus** [comment]
> should I squash?

Let's let the bots do the work :)
/label tide/merge-method-squash
/hold cancel

**Comment by justaugustus** [comment]
> How do we announce this so it doesn't surprise folks?

We'll announce for the next release.

**Pull request merged**
