### PR TITLE
Reuse signer in `DefaultPromoterImplementation`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This uses the new `SignImageWithOptions` API to reuse the signer and therefore its caching.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes-sigs/release-engineering PTAL

I think we can cut a new kpromo after this.

**Comment by cpanato** [comment]
> @kubernetes-sigs/release-engineering PTAL
> 
> I think we can cut a new kpromo after this.

i can help to cut those things

**Comment by saschagrunert** [comment]
> > @kubernetes-sigs/release-engineering PTAL
> > I think we can cut a new kpromo after this.
> 
> i can help to cut those things

Thank you so much!

**Comment by jeremyrickard** [comment]
/lgtm 

thanks @saschagrunert

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
