### PR TITLE
Use recursive signing for multi-arch images

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Update the release-sdk and set the option to `true`.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
PTAL @kubernetes-sigs/release-engineering 

We would require a new kpromo release for this.
#### Does this PR introduce a user-facing change?

```release-note
Use recursive signing for multi-arch images.
```

### CODE REVIEW

**Comment by cpanato** [comment]
saw some times, but not 100% sure :/

**Comment by cpanato** [comment]
@saschagrunert maybe can we open a test PR to check if the test will pass and maybe we try to fix there if is a flake? i can open the PR and we check, wdyt?

**Comment by saschagrunert** [comment]
> @saschagrunert maybe can we open a test PR to check if the test will pass and maybe we try to fix there if is a flake? i can open the PR and we check, wdyt?

Sounds good to me!

**Comment by cpanato** [comment]
> > @saschagrunert maybe can we open a test PR to check if the test will pass and maybe we try to fix there if is a flake? i can open the PR and we check, wdyt?
> 
> Sounds good to me!

it passes in the first try https://github.com/kubernetes-sigs/promo-tools/pull/869 🤔

**Comment by saschagrunert** [comment]
@cpanato PTAL, looks like the recursive signing is adding layers as well.

**Review by cpanato — APPROVED** [review]
thanks
/lgtm

**Pull request merged**
