### PR TITLE
Docs reshuffle

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup documentation

#### What this PR does / why we need it:

- docs: Init directory
- docs: Split README.md into multiple files
- docs: Move file promotion instructions to separate file
- docs: Move kpromo.md to top-level README.md
- README.md: Rewrite to focus on kpromo
- docs: Copy in image promotion PR instructions from k/sig-release
- docs: Add audience disclaimer atop image promotion PR doc

#### Which issue(s) this PR fixes:

Fixes [#450](https://github.com/kubernetes-sigs/promo-tools/issues/450)
FYI @johngmyers

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Consider this a first step in getting the documentation for this repo in a better state, but miles away from perfect.
Let's lock in the docs restructure and then iterate on improvements in future PRs.

/assign @puerco @Verolop @saschagrunert @cpanato 
cc: @kubernetes-sigs/release-engineering

**Comment by puerco** [comment]
Wow, this is a super nice docs update, thanks a lot @justaugustus ! I think we should discuss creating an easy starter guide for projects to start using file/image promotion. For example, if I know I need to promote images things are super clear:

> Using CIP to promote images requires four pieces:
> 1. promoter manifest(s)
> 2. source registry
> 3. destination registry
> 4. service account for writing into destination registry

I propose to write the guide previous to that doc. An entry point to send project owners beginning the journey, WDYT?

Anyway, thanks for this one!
/lgtm

**Comment by justaugustus** [comment]
> I propose to write the guide previous to that doc. An entry point to send project owners beginning the journey, WDYT?

For sure! I see a lot of different paths to explore:
- I just want to grab the tool and automagically create image promotion PRs
- I want know a little bit about the architecture of this tool
- I'm a Release Manager/potential maintainer and I need to know everything about how this works

There's another axis to consider:
- Am I using this tool/subcommand as a user
- Am I actually a bot that needs to run this unattended

**Comment by puerco** [comment]
Yes, that's great stuff! I've added it to a new issue: https://github.com/kubernetes-sigs/promo-tools/issues/463

**Pull request merged**
